### ISSUE TITLE
Configure which columns should be indexed

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#114]
#111 (#101) introduced generalized columns, but hardcoded the columns that should be indexed (or sorted by in the the case of dates). Align on how we want to configure this and implement it.

**Comment by fengelniederhammer** [comment]
Example as discussed:
```
schema:
  instanceName: test
  metadata:
    - name: gisaid_epi_isl
      type: string
    - name: date
      type: date
    - name: unsorted_date
      type: date
    - name: region
      type: string
      index: true
    - name: country
      type: string
    - name: pango_lineage
      type: pango_lineage
      generateIndex: false -> Fehler
  primaryKey: gisaid_epi_isl
  dateToSortBy: date
  partitionBy: pango_lineage
```

* Every string metadata should accept a field `generateIndex` (boolean). The default is false.
  * Pangolineages are indexed by default. `generateIndex: false` should throw an exception.
  * Dates should not be indexed.
  * When implementing number columns, we'll have to talk again about indexing them.
* `dateToSortBy: date` references a date column that the partitions should be sorted by. If absent, partitions should not be sorted.
* `partitionBy: pango_lineage` should reference any column. This is mandatory.
